### ISSUE TITLE
Can't use rails helper methods like `surround` in cells

### ISSUE THREAD

**Issue by PikachuEXE** [hamlit/cells-hamlit2#1]
Since `surround` call `output.chomp`, but `capture_haml` calls `capture` and `capture` in `cells-hamlit2` returns an output buffer object

I looked at [the method source code for `capture`](https://github.com/hamlit/cells-hamlit2/blob/master/lib/cell/hamlit.rb#L34) :
```ruby
def capture(*args)
  value = nil
  buffer = with_output_buffer { value = yield(*args) }
  buffer.to_s if buffer.size > 0
  value
end
```
I wonder if there is a missing return for the line `buffer.to_s if buffer.size > 0`
Edit 1: I override the `capture` method and added `buffer.to_s if buffer.size > 0`, now it works fine

### Error message
```
undefined method `chomp' for #<Cell::ViewModel::OutputBuffer:0x00007ffca094e748>
```

**Comment by k0kubun** [comment]
Could you make PR that includes a failing test? I'll fix it in cells-hamlit2 if it is available.

**Comment by PikachuEXE** [comment]
Problem is I don't know if this should be fixed in this gem or in the helper
@apotonick might not want any "output buffer" in `cells-hamlit`
And this gem is only for workaround

**Comment by apotonick** [comment]
The goal should be not needing an output buffer, look at how we do it in the erbse gem: we simple return the "captured" content from the `capture` method, because capture is built into the template language itself. This is how it should've been done in all the Rails tpl engines and helpers in the first place, because you don't need any state management like `if buffer.size` etc. 

Maybe hamlit could support that?

**Comment by k0kubun** [comment]
> The goal should be not needing an output buffer, look at how we do it in the erbse gem: we simple return the "captured" content from the capture method, because capture is built into the template language itself. 

[This one](https://github.com/trailblazer/cells-erb/blob/46edd1e3e546d14b610aed0d17bd899091492f1a/lib/cell/erb/template.rb#L13-L15), right?

> Maybe hamlit could support that?

Yes, at least with hamlit-block. But hamlit-block breaks behavior outside cells. So hamlit needs built-in `capture` support like erbse.

As Haml has more complex semantics than Slim and erb, currently it's not achieved to have capture support without breaking other behaviors. So now we're using output buffer but I'll surely replace current implementation after Hamlit provides `capture_haml` helper for non-Rails environments.

For now, I fixed this for current implementation https://github.com/hamlit/cells-hamlit2/pull/2.
